### ISSUE TITLE
checkShouldContinue in plugins-shared 0.0.1 has no boolean return

### ISSUE THREAD

**Issue by btraut** [timsexperiments/es-exec#6]
I'm trying to use the start plugin in my repo, but it silently fails. Some investigation led me to find that the `checkShouldContinue` returns void for all branches in v0.0.1. Looks like you've already fixed this in v0.0.2, but you haven't created a release to npm. Without that, I'm unable to use the plugin directly (I worked around by forking for now).

Do you plan to release a v0.0.2 build soon?

btw, I really appreciate the simplicity of these plugins.

**Comment by timsexperiments** [comment]
Appreciate the feedback!

Just published all of the packages to version 0.0.3 forgot to update the references between the projects.

Planning to add an action to autmatically publish this for me once I get the time.
